version: "2.3"

services:
  web:
    image: py-dir-listing
    build: .
    stop_signal: SIGINT       # python listens to SIGINT, not SIGTERM
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ${MNTDIR}
        target: /var/www/Pictures
        read_only: true
